# PyInstaller spec — one-folder Windows app. Do not commit dist/.
# Run: powershell -File scripts/build_spider_app.ps1

block_cipher = None
a = Analysis(
    ["tools/campaign_gui.py"],
    pathex=["src"],
    binaries=[],
    datas=[
        ("deals/4925153.txt", "deals"),
        ("docs/research/f2_quality_frontier_v0_84.json", "docs/research"),
        ("docs/research/long_horizon_f2_adjudication_v0_92.json", "docs/research"),
        ("docs/research/proof_aware_tactical_bridge_v0_80.json", "docs/research"),
        ("docs/research/g158_proof_aware_f4_v0_81.json", "docs/research"),
        ("docs/research/strong_surplus_f4_bridge_v0_87.json", "docs/research"),
        ("docs/research/long_horizon_f3_adjudication_v0_91.json", "docs/research"),
        ("docs/research/f5_production_candidate_v0_97.json", "docs/research"),
        ("docs/research/f3_bridge_calibration_v0_83.json", "docs/research"),
        ("solutions/4925153_incumbent.json", "solutions"),
        ("solutions/4925153_autonomous_v0_100.moves", "solutions"),
        ("solutions/4925153_autonomous_v0_100.json", "solutions"),
        ("solutions/4925153_autonomous_v0_74.moves", "solutions"),
    ],
    hiddenimports=[
        "spider.campaign_worker",
        "spider.campaign_scheduler",
        "spider.campaign_store",
        "spider.campaign_bundle",
        "spider.campaign_exchange",
        "spider.campaign_import_v084",
        "spider.campaign_closed",
        "spider.campaign_promote",
        "spider.campaign_schedule",
        "spider.campaign_autonomous",
        "spider.campaign_expand",
        "spider.campaign_nodes",
        "spider.campaign_status",
        "spider.incumbent",
        "spider.consequence_search",
        "spider.assembly_lower_bound",
        "spider.assembly_policy",
        "spider.tactical_integration",
        "spider.app_paths",
        "spider.hardware",
        "spider.hardware_profile",
        "spider.resource_policy",
        "spider.search_kernel",
        "spider.packed_state",
        "spider.whole_game_anytime",
        "psutil",
        "tkinter",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="SpiderCampaign",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name="SpiderCampaign",
)
